In [1]:
import numpy as np
 
students = np.array([
    [101, 78, 85, 92, 88], # id,maths,english,computer,science
    [102, 65, 72, 70, 68],
    [103, 90, 95, 91, 94],
    [104, 45, 55, 60, 50],
    [105, 82, 79, 85, 80],
    [106, 55, 60, 58, 62],
    [107, 88, 92, 86, 90],
    [108, 72, 68, 75, 70],
    [109, 95, 91, 96, 94],
    [110, 40, 48, 45, 42]
])
 
print(students)

[[101  78  85  92  88]
 [102  65  72  70  68]
 [103  90  95  91  94]
 [104  45  55  60  50]
 [105  82  79  85  80]
 [106  55  60  58  62]
 [107  88  92  86  90]
 [108  72  68  75  70]
 [109  95  91  96  94]
 [110  40  48  45  42]]


In [2]:
#shape,size,dimention
print("Shape:", students.shape) #10 rows, 5 columns
print("Size:", students.size) #no. of elements
print("Dimentions", students.ndim) #2d


Shape: (10, 5)
Size: 50
Dimentions 2


In [3]:
#access single student
print(students[0]) #math, eng, com, sci

[101  78  85  92  88]


In [4]:
#specific marks mah
print(students[0,3]) # rows=0 and cols=1

92


In [5]:
#specific makrs maths col and row 3
#specific makrs eng col and row 5
#specific makrs com col and row 6

print(students[2,1])
print(students[4,2])
print(students[5,3])
#specific makrs stu_id col and row 7
#print(students[rows,columns])
print(students[6,0])


90
79
58
107


In [6]:
#forst 3 students 1 to 3
print(students[0:3])

#GET STUDENTS FROM 4 to 8
print(students[3:8])

# get students from 5 to 8 only maths coln
print(students[4:3,1])

[[101  78  85  92  88]
 [102  65  72  70  68]
 [103  90  95  91  94]]
[[104  45  55  60  50]
 [105  82  79  85  80]
 [106  55  60  58  62]
 [107  88  92  86  90]
 [108  72  68  75  70]]
[]


In [7]:
#last 3 students
print(students[-3:])

[[108  72  68  75  70]
 [109  95  91  96  94]
 [110  40  48  45  42]]


In [8]:
#first 3 students with id and math
print(students[:3,0:2])

[[101  78]
 [102  65]
 [103  90]]


In [9]:
#extract maths
maths = students [:,1] #all rows, 1 coln
print(maths)

[78 65 90 45 82 55 88 72 95 40]


In [10]:
#first 5 students marks
print(students[:5,1:])

[[78 85 92 88]
 [65 72 70 68]
 [90 95 91 94]
 [45 55 60 50]
 [82 79 85 80]]


In [11]:
#maths, eng, com, sci
#maths and eng

print(students[:,1:3])

[[78 85]
 [65 72]
 [90 95]
 [45 55]
 [82 79]
 [55 60]
 [88 92]
 [72 68]
 [95 91]
 [40 48]]


In [12]:
# com and sci
print(students[:,3:5])

[[92 88]
 [70 68]
 [91 94]
 [60 50]
 [85 80]
 [58 62]
 [86 90]
 [75 70]
 [96 94]
 [45 42]]


In [16]:
# reverse data set (row_start: row_stop: row_step, )
print(students[::-1]) # last rows becomes first
print("Reverse skip by 2")
print(students[::-2])

[[110  40  48  45  42]
 [109  95  91  96  94]
 [108  72  68  75  70]
 [107  88  92  86  90]
 [106  55  60  58  62]
 [105  82  79  85  80]
 [104  45  55  60  50]
 [103  90  95  91  94]
 [102  65  72  70  68]
 [101  78  85  92  88]]
Reverse skip by 2
[[110  40  48  45  42]
 [108  72  68  75  70]
 [106  55  60  58  62]
 [104  45  55  60  50]
 [102  65  72  70  68]]


In [18]:
# reverse subject order (column change)
print(students[:,1:][:,::-1])

[[88 92 85 78]
 [68 70 72 65]
 [94 91 95 90]
 [50 60 55 45]
 [80 85 79 82]
 [62 58 60 55]
 [90 86 92 88]
 [70 75 68 72]
 [94 96 91 95]
 [42 45 48 40]]


In [19]:
#reverse subject order/ alternative way
f= students[:,1:]
print(f[:,::-1])

[[88 92 85 78]
 [68 70 72 65]
 [94 91 95 90]
 [50 60 55 45]
 [80 85 79 82]
 [62 58 60 55]
 [90 86 92 88]
 [70 75 68 72]
 [94 96 91 95]
 [42 45 48 40]]


In [27]:
#total | sum of marks of all subjects and particular student
marks = students[:,1:]
total= np.sum(marks, axis = 1) #by default row but we need columns
print(total)

# alternatively
for i in range(len(marks)):
    count=0
    for j in range(4):
        count += marks[i][j]
    print(f"students {i} marks {count}")
    

[343 275 370 210 326 235 356 285 376 175]
students 0 marks 343
students 1 marks 275
students 2 marks 370
students 3 marks 210
students 4 marks 326
students 5 marks 235
students 6 marks 356
students 7 marks 285
students 8 marks 376
students 9 marks 175
